name: proxysit
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - xarray
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - cartopy
  - calendar
  - shapefile
  - shapely
  - glob
  - geopandas
  - h5py
  - hdf4
  - hdf5
  - rasterio
  
  